### ISSUE TITLE
Buy tokens: delivery_address is not optional

### ISSUE THREAD

**Issue by davepuchyr** [iov-one/savitar-widgets#1]
When I try to buy tokens and click the `Get Started` button I get the following:

```
Error: SavitarWidget: Missing delivery_address
    at payments.js:1
    at uo (framework.4dd1003….js:1)
    at Nu (framework.4dd1003….js:1)
    at t.unstable_runWithPriority (framework.4dd1003….js:1)
    at $l (framework.4dd1003….js:1)
    at Pu (framework.4dd1003….js:1)
    at framework.4dd1003….js:1
    at U (framework.4dd1003….js:1)
    at MessagePort.T.port1.onmessage (framework.4dd1003….js:1)
```

![Selection_032](https://user-images.githubusercontent.com/5599538/93990809-df7cc900-fd8b-11ea-8f46-5e793b6e10ac.png)

@savitar-dev, how can a user specify `delivery_address`?  As far as I can tell, it can only be specified in the config on the server side.

**Comment by davepuchyr** [comment]
I'm using https://github.com/savitar-exchange/swap-sdk.git#a467f26baf8a4c8c63338c885e879bd6c22cb330.

**Comment by jloup** [comment]
Can you provide us with widget configuration ? 

I think you set payment_type to 'merchant' or 'exchange'.

If you want params to be optional, just leave payment_type empty. 'merchant' and 'exchange' validates configuration against a use case. I will update the doc.

**Comment by davepuchyr** [comment]
> Can you provide us with widget configuration ?
> 
> I think you set payment_type to 'merchant' or 'exchange'.
> 
> If you want params to be optional, just leave payment_type empty. 'merchant' and 'exchange' validates configuration against a use case. I will update the doc.

You are correct.  I had 
```
 const configTokens = {
    payment_type: "merchant",
    email: "tokens@example.com",
    email_editable: true,
    currency: "iov",
    amount: 100,
    amount_editable: true,
    delivery_address: "star1...",
 };
```
